services:
  app:
    build: .
    ports:
      - 80:3000
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodbdata:/data/db
  redis:
    image: redis:5-alpine
    volumes:
      - redis:/data
    restart: unless-stopped
volumes:
  mongodbdata:
  redis: